### ISSUE TITLE
Git hooks are not executed (on the correct .git/index)

### ISSUE THREAD

**Issue by nathanael-ruf** [gitbutlerapp/gitbutler#2615]
For me git pre-commit hooks aren't executed.
Judging from https://github.com/gitbutlerapp/gitbutler/issues/2551 it seems like they should be, just without being able to view the output?

**Comment by nolith** [comment]
Same for me, I was testing a new command I added in lefthook and I noticed that gitbutler happily committed something that was supposed to make the pre-commit check fail

**Comment by nolith** [comment]
I'm using https://github.com/evilmartians/lefthook and it installs a script like this one.

```
 cat .git/hooks/pre-commit
#!/bin/sh

if [ "$LEFTHOOK" = "0" ]; then
  exit 0
fi

call_lefthook()
{
  dir="$(git rev-parse --show-toplevel)"
  osArch=$(uname | tr '[:upper:]' '[:lower:]')
  cpuArch=$(uname -m | sed 's/aarch64/arm64/')

  if lefthook -h >/dev/null 2>&1
  then
    lefthook "$@"
  elif test -f "$dir/node_modules/lefthook/bin/index.js"
  then
    "$dir/node_modules/lefthook/bin/index.js" "$@"
  elif test -f "$dir/node_modules/@evilmartians/lefthook/bin/lefthook_${osArch}_${cpuArch}/lefthook"
  then
    "$dir/node_modules/@evilmartians/lefthook/bin/lefthook_${osArch}_${cpuArch}/lefthook" "$@"
  elif test -f "$dir/node_modules/@evilmartians/lefthook-installer/bin/lefthook_${osArch}_${cpuArch}/lefthook"
  then
    "$dir/node_modules/@evilmartians/lefthook-installer/bin/lefthook_${osArch}_${cpuArch}/lefthook" "$@"
  elif bundle exec lefthook -h >/dev/null 2>&1
  then
    bundle exec lefthook "$@"
  elif yarn lefthook -h >/dev/null 2>&1
  then
    yarn lefthook "$@"
  elif pnpm lefthook -h >/dev/null 2>&1
  then
    pnpm lefthook "$@"
  elif command -v npx >/dev/null 2>&1
  then
    npx lefthook "$@"
  elif swift package plugin lefthook >/dev/null 2>&1
  then
    swift package --disable-sandbox plugin lefthook "$@"
  else
    echo "Can't find lefthook in PATH"
  fi
}

call_lefthook run "pre-commit" "$@"
```

**Comment by nolith** [comment]
@krlvi this morning I was on another mac and decided to test if this issue was depending on my machine.

I started with your pre-commit hook and it worked as expected, then I added a `lefthook.yml` with a pre-commit command that calls `false` and tested it with `git`, it worked as well, but in gitbutler it does not work, the commit is generated

**Comment by nolith** [comment]
I think I found where is the issue, `lefthook` seems to interact with the staged files and I'm quite sure gitbutler don't make use of it.

With a bunch of `eprintln!` and some tweak to the lefthook generated `pre-commit` file I managed to confirm that gitbutler invokes `lefthook` but then lefthook skips all the validation because it thinks that the staging area is empty.


```
╭──────────────────────────────────────╮
│ 🥊 lefthook v1.5.6  hook: pre-commit │
╰──────────────────────────────────────╯
│  fail (skip) no matching staged files

  ────────────────────────────────────
summary: (skip) empty
``` 

In the above output, _fail_ is the name of the command that should run `false` and always fail.


I'll give a try with other git-hooks managers, but `lefthook` is incompatible with gitbutler.

**Comment by yeliex** [comment]
@nolith husky for node ecosystem  not work as well

**Comment by schacon** [comment]
Ah, yeah. I see what the problem is. We don't use the index for staging the next commit. We can't, because we basically do that in memory. We keep the index matching what the union of the commit trees on our applied branches are, so status works more or less how you expect, but we don't actually use it to commit. So if pre-commit relies on that (which makes sense) rather than the working directory, then it's not going to match what is about to be committed in the virtual branch.

I'm actually not sure of a good way around this. Perhaps we can replace the index right before running this command and then revert it after.

**Comment by jhnns** [comment]
Damn, I'm also using `husky` and `lint-staged` 😁. Is there any plan to fix this or is GitButler's approach just incompatible with `husky`/`lint-staged`?

**Comment by borama** [comment]
It seems that the same issue is with [Overcommit](https://github.com/sds/overcommit?tab=readme-ov-file#precommit) as well. No pre-commit hooks are run for me.

**Comment by senritsu** [comment]
Seems like this is still an issue, any plans or workarounds on how to work with common setups like `husky`+`lint-staged`? I'd really love trying this one out, but currently can't due to this 😞

**Comment by Byron** [comment]
I think `lint-staged` can't work as long as the staging area isn't used. With that said, I think it would be possible to manufacture an index with what would be changed and run pre-commit hooks accordingly. This should be quite straightforward for user-initiated commits. 

What's unclear to me is how these hooks would communicate a result - right now [I don't think there are facilities for that](https://github.com/gitbutlerapp/gitbutler/blob/c8a591505aec935ec08573d9217ccbe9f576fcac/crates/gitbutler-branch-actions/src/virtual.rs#L777).

**Comment by Byron** [comment]
It's definitely on the radar of @mtsgrd and we will make efforts to make GitButler a "good gitizen" - it's going to happen.

**Comment by mtsgrd** [comment]
@snowbillr the pr above this comment works on my machine, just need to validate the approach with the rest of the team and with respect to the upcoming v3 re-design changes. I will hopefully be able to land it soon, and include it in the next release! Thank you for being patient. :)

**Comment by snowbillr** [comment]
That's fantastic to hear, thanks for putting the effort to all of this. GitButler is really changing my workflow for the better when I can use it. Having pre-commit work with it is going to unlock it even further.

**Comment by Caleb-T-Owens** [comment]
@snowbillr It's really encouraging to hear that! Thanks for bearing with us while we work through these issues

**Comment by indaco** [comment]
Hi all,

First of all, thanks for the amazing work on GitButler — it’s truly changed the way I work with Git, giving me much more flexibility and control.

One thing I’m struggling with is getting Git hooks to run properly. I always enable the **“Run commit hooks”** toggle in my project settings, since I always rely on hooks in my workflow.

I usually store my hook scripts in a `.githooks` folder and set it with:

```bash
git config core.hooksPath .githooks
```

However, the hooks are never executed (yes, they are set as executables: `chmod +x .githooks/*`). I also tried using the default `git/hooks` directory, but unfortunately, the result is the same — they still don’t run. Specifically, I’m trying to use `pre-commit` and `pre-push` hooks.

I’m not sure if I’m doing something wrong or if there’s a limitation I’m missing. I’d really love to get this working, as commit hooks are a critical part of my development flow.

Any help or insights would be greatly appreciated — and again, thanks for all your great work on GitButler!

**Comment by Byron** [comment]
Thanks a lot for bringing this up - it might be worth it's own issue though as it seems related to `core.hooksPath`.
Since it appears to be set directly in the repository-local configuration, I'd think that [`git2-hooks`](https://docs.rs/git2-hooks/latest/git2_hooks/) will pick it up - it says so right in the configuration.

If this variable would be set with more complex include-if based configuration it could be that `git2` can't pick it up due to lack of support.

In any case, I'd appreciate if a new issue is created if you'd like to dig in deeper.
Thank you.

**Comment by Caleb-T-Owens** [comment]
Hey! We do now correctly stage the right hunks when running pre-commit hooks, so this should be resolved :+1:

**Comment by flazouh** [comment]
So lefthook works correctly ?

```yml
pre-commit:
  parallel: true
  output:
    - meta
    - summary
    - success
    - failure
    - execution
    - execution_out
    - execution_info
  commands:
    # Lint staged files
    lint-staged-backend:
      glob: "packages/backend/**/*.{ts,tsx,js,jsx,json,jsonc}"
      run: |
        cd packages/backend
        for file in {staged_files}; do
          rel_file="${file#packages/backend/}"
          bunx @biomejs/biome check --write "$rel_file"
        done
      stage_fixed: true
    
    lint-staged-extension:
      glob: "packages/extension/**/*.{ts,tsx,js,jsx,json,jsonc}"
      run: |
        cd packages/extension
        for file in {staged_files}; do
          rel_file="${file#packages/extension/}"
          bunx @biomejs/biome check --write "$rel_file"
        done
      stage_fixed: true
    
    # Type check all packages (always runs, regardless of staged files)
    # Note: These commands run on every commit attempt, even with no staged files
    typecheck:
      run: bun run typecheck
      fail_text: "❌ Typecheck failed. Please fix type errors before committing. You CANNOT use any ts-ignore, ts-expect-error, or similar TypeScript ignore directives by any means."
    
    # Run all tests (always runs, regardless of staged files)
    # Note: These commands run on every commit attempt, even with no staged files
    test:
      run: bun run test
      fail_text: "❌ Tests failed. Please fix failing tests before committing."

pre-push:
  parallel: true
  output:
    - meta
    - summary
    - success
    - failure
    - execution
    - execution_out
    - execution_info
  commands:
    # Type check all packages (always runs, regardless of staged files)
    typecheck:
      run: bun run typecheck
      fail_text: "❌ Typecheck failed. Please fix type errors before pushing. You CANNOT use any ts-ignore, ts-expect-error, or similar TypeScript ignore directives by any means. You CANNOT use --no-verify to push code under any circumstances."
    
    # Run all tests (always runs, regardless of staged files)
    test:
      run: bun run test
      fail_text: "❌ Tests failed. Please fix failing tests before pushing. You CANNOT use --no-verify to push code under any circumstances."
    
    # Build all packages (always runs, regardless of staged files)
    build:
      run: bun run build
      fail_text: "❌ Build failed. Please fix build errors before pushing. You CANNOT use --no-verify to push code under any circumstances."

```

this triggered the linting on the WHOLE codebase, is that normal ?


<img width="881" height="966" alt="Image" src="https://github.com/user-attachments/assets/193c20a4-55f4-40ed-8187-cd5a7d2ba57a" />

Also cannot close this panel.
