### ISSUE TITLE
trying to update workspace, getting "Unhandled exception: Branch statuses must not be empty"

### ISSUE THREAD

**Issue by brianloveswords** [gitbutlerapp/gitbutler#6214]
screenshot of the error toast:
<img width="323" alt="Image" src="https://github.com/user-attachments/assets/c9ce63e1-96fc-4afa-9de5-41c1757b35e9" />

anything I can do to manually get past this error using git cli? i don't want to mess up my GitButler workspace.

**Comment by brianloveswords** [comment]
also, let me know if you need any more information for debugging and I'll provide what I can

**Comment by Byron** [comment]
Thanks a lot for reporting!

The error messages originates here:

https://github.com/gitbutlerapp/gitbutler/blob/45730cc8515355dad9da57febfc2e417f0d30ad5/crates/gitbutler-branch-actions/src/upstream_integration.rs#L88-L97

Following the code just a little bit seems to indicate that it *could* run into this if there was not a single branch. Having a workspace would imply this is the case though, but maybe there is an empty stack, i.e. a stack without any branches?

This of course shouldn't be possible, but seems to be a plausible reason for running into this.

In order to workaround this error, I think one would have to try and manually delete the empty stack in `.git/gitbutler/virtual_branches.toml`. If it doesn't contain sensitive information, you could post it here and we take it from there.

> anything I can do to manually get past this error using git cli?

Unfortunately that's not yet possible.

**Comment by Byron** [comment]
Thanks for sharing!

Even though I still don't know if there is a workaround or what's truly causing this, I'd hope that it resolves itself once the new major release is available. A lot of the old codepaths won't be exercised anymore then.

**Comment by brianloveswords** [comment]
sorry for the delay in getting this to you, here's what my `virtual_branches.toml` looks like. let me know if there's anything I can manually fiddle with to get unblocked!


```toml
[default_target]
branchName = "main"
remoteName = "origin"
remoteUrl = "REDACTED"
sha = "c49fc54067a0dfdae3db4fc49cec3d7a69f85548"
pushRemoteName = "origin"

[branch_targets]

[branches.a14ded4f-1ba4-42ce-b481-eb90e3acaf87]
id = "a14ded4f-1ba4-42ce-b481-eb90e3acaf87"
name = "Lane"
notes = ""
created_timestamp_ms = "1737585713440"
updated_timestamp_ms = "1739220072161"
tree = "8868a58a54c11c4fe70c32787e4e64796c48cd31"
head = "d2cbc78f67bfc8d46dfc2e5d886b33923aabba90"
ownership = """
brian.brennan/2025-01 sip tiers v2/sql/1-setup.sql:74-90-9599a69ad51b3c1ccbc1d440c020d019,49-71-ca9734a34e44ac18e36233904c6735b3,29-48-7364be8420c5c9b769d4d023f89e8418
"""
order = 0
selected_for_changes = 1738518866532
allow_rebasing = true
in_workspace = true
post_commits = false

[[branches.a14ded4f-1ba4-42ce-b481-eb90e3acaf87.heads]]
name = "bjb/sip-ratios"
archived = false

[branches.a14ded4f-1ba4-42ce-b481-eb90e3acaf87.heads.head]
ChangeId = "cf194ac4-720f-4516-8cab-b65645975956"

[branches.483caff1-5409-4f71-b223-0f19d0af63e4]
id = "483caff1-5409-4f71-b223-0f19d0af63e4"
name = "Lane 1"
notes = ""
created_timestamp_ms = "1737669560680"
updated_timestamp_ms = "1738202133969"
tree = "7d477802dfad180d4c5020a394b8c464db118841"
head = "c49fc54067a0dfdae3db4fc49cec3d7a69f85548"
ownership = """
brian.brennan/2025-01 cross ctc activity/analysis.sql:1-114-ca2f5661b28ff351b18aa03b60a5baa6
brian.brennan/2025-01 cross ctc activity/analysis.sh:1-4-5f03d29b74b4eaa16c1066cd8c4392a8
brian.brennan/2025-01 cross ctc activity/README.md:1-13-f126e61d896b4a27ddfe396081696599
brian.brennan/2025-01 cross ctc activity/.gitignore:1-11-b980666f823ad365a08627aa372f222a
"""
order = 1
allow_rebasing = true
in_workspace = true
post_commits = false

[[branches.483caff1-5409-4f71-b223-0f19d0af63e4.heads]]
name = "bjb/cross-ctc"
archived = true

[branches.483caff1-5409-4f71-b223-0f19d0af63e4.heads.head]
CommitId = "c49fc54067a0dfdae3db4fc49cec3d7a69f85548"
```
