### ISSUE TITLE
Can't create PR after upgrade

### ISSUE THREAD

**Issue by CGQAQ** [gitbutlerapp/gitbutler#8526]
### Version

0.14.21

### Operating System

Windows

### Distribution Method

msi (Windows)

### Describe the issue

![Image](https://github.com/user-attachments/assets/5c4cd7d4-66f4-4af4-a36d-8781d1fd3990)

![Image](https://github.com/user-attachments/assets/33e8964a-2761-4e24-8cae-6a1979169aa7)

Edit 1
The project is renamed, I have changed the remote URL, but gitbutler seems not picked it up.
![Image](https://github.com/user-attachments/assets/0946a3ce-787c-43f1-9097-ce712b9a2431)

### Relevant log output (Optional)

```shell

```

**Comment by Byron** [comment]
Thanks a lot for reporting!

It does indeed appear that the remote URL is cached in `.git/gitbutler/virtual_branches.toml`, which can probably lead to issues like this.

Could you try to perform the URL renaming in the aforementioned file as well? You are looking for the `remoteUrl` field at the very top of the file.

```toml
[default_target]
branchName = "master"
remoteName = "origin"
remoteUrl = "https://github.com/Byron/small"
sha = "8efa618cccf907a13e0502fc603fa30efbf5d99a"
pushRemoteName = "origin"

[..]
```

Thanks again.
