### ISSUE TITLE
git submodule setting `ignore = all` should be followed

### ISSUE THREAD

**Issue by koppor** [gitbutlerapp/gitbutler#8792]
### Version

0.14.26

### Operating System

Windows

### Distribution Method

msi (Windows)

### Describe the issue

I have **all** my submodules set to `ignore`. In older versions, they did not show up as changes.

```toml
[submodule "abbrv.jabref.org"]
  path = jablib/src/main/abbrv.jabref.org
  url = https://github.com/JabRef/abbrv.jabref.org.git
  ignore = all
  shallow = true
[submodule "csl-styles"]
  path = jablib/src/main/resources/csl-styles
  url = https://github.com/citation-style-language/styles.git
  ignore = all
  shallow = true
[submodule "csl-locales"]
  path = jablib/src/main/resources/csl-locales
  url = https://github.com/citation-style-language/locales.git
  ignore = all
  shallow = true
```

Now, they do:

![Image](https://github.com/user-attachments/assets/fe9174c4-83bb-41ee-b723-a864ae46a6fc)

---

Seems to be the opposite of https://github.com/gitbutlerapp/gitbutler/issues/5749

### Relevant log output (Optional)

```shell

```
